# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cold_Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('consist', models.CharField(max_length=100)),
            ],
        ),
    ]
