# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('consist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hot_Appetizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('consist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('consist', models.CharField(max_length=100)),
            ],
        ),
    ]
