# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_first_courses_hot_appetizers_salad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cold_dishes',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
