# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_cold_dishes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_courses',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='hot_appetizers',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='salad',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
