# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20161119_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cold_dishes',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='first_courses',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='hot_appetizers',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
    ]
