# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20161120_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('decrib', models.CharField(max_length=1000)),
                ('res', models.IntegerField(default=0)),
            ],
        ),
    ]
