# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Labs',
        ),
    ]
