# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20161213_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
